version: "3.9"
services:
  ferri-log-server:
    hostname: Ra
    image: ferri-log-srv
    ports:
      - 8443:8443
  rsyslog-clt-1:
    hostname: Horus
    image: rsyslog-clt
  rsyslog-clt-2:
    hostname: Ozyrys
    image: rsyslog-clt
  persistence-db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ferri-log
  cache-db:
    image: skytable/sdb:v0.7.5
    ports:
      - 2003:2003
    container_name: mysky
    volumes:
      - /tmp/ferri-log/skytable:/var/lib/skytable
