[application]
folder_to_watch = "/var/log/remote"
host = "0.0.0.0"
one_request_replenishment_time = 5
port = 8443
request_pool = 10

[certificates]
ca_cert_path = "certs/rootCA.pem"
server_cert_path = "certs/ferri-log.com.pem"
server_key_path = "certs/ferri-log.com-key.pem"

[database]
database_name = "ferri-log"
host = "persistence-db"
password = "postgres"
port = 5432
require_ssl = false
username = "postgres"

[cache]
host = "cache-db"
port = 2003
