[package]
edition = "2021"
name = "ferri-log-core"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.21"
uuid = "1.1.2"
