[application]
folder_to_watch = "/var/log/remote/DESKTOP-J7C3HE9"
host = "localhost"
port = 8080

[database]
database_name = "ferri-log"
host = "localhost"
password = "postgres"
port = 5432
require_ssl = false
username = "postgres"
